ConditionalComponentStyle
triniti/apple-news-php pull request #16
Opened 2021-04-21 18:40 UTC by bhsiao55

* Add `Triniti\AppleNews\Style\ConditionalComponentStyle` to enable conditional properties for component style.

2021-04-22 23:05 UTC, arunkarnati requested changes

2021-04-22 23:05 UTC, arunkarnati commented on src/Style/ComponentStyle.php
> +        if (null !== $conditionals) {
@bhsiao55 - please use `empty` fn to check since it checks for the falsy value and also update all the other usages.

2021-04-22 23:05 UTC, arunkarnati commented on tests/Style/ComponentStyleTest.php
> +    /**
@bhsiao55 - nit: the doc block is not needed here since it doesn't give any extra info other than the fn name.

2021-04-22 23:55 UTC, arunkarnati commented on src/Style/ComponentStyle.php
> +    public function setConditional(?array $conditionals = []): self
@bhsiao55 - I just noticed that we have methods like this in a few other places, leave it as is for now. We will change all of these some other time.

2021-04-23 00:17 UTC, bhsiao55 commented on src/Style/ComponentStyle.php
> +    public function setConditional(?array $conditionals = []): self
we have the same methods in other components that are already being used so let's keep it the way it is to say consistent

2021-04-23 18:39 UTC, arunkarnati approved these changes

2021-04-23 20:20 UTC, bhsiao55 commented
@gdbrown can you take a final look and tag?

2021-04-23 20:26 UTC, gdbrown commented
@bhsiao55 these changes also need to go into new triniti/core lib

2021-04-23 20:26 UTC, merged